services:
  db:
    build: ./db
    container_name: store-db
    tty: true
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=store
    volumes:
      - ./db/db_data:/var/lib/mysql
